name: ${name}
version: '${version}'
main: me.xginko.villageroptimizer.VillagerOptimizer
authors: [ xGinko ]
description: ${description}
website: ${url}
api-version: '1.21'
softdepend:
  - AntiVillagerLag
folia-supported: true

commands:
  villageroptimizer:
    usage: /villageroptimizer [ reload, version, disable ]
    description: VillagerOptimizer admin commands
    aliases:
      - voptimizer
      - vo
  optimizevillagers:
    usage: /optimizevillagers <blockradius>
    description: Optmize villagers in a radius around you
    aliases:
      - optvils
      - noai
  unoptimizevillagers:
    usage: /unoptimizevillagers <blockradius>
    description: Unoptmize villagers in a radius around you
    aliases:
      - unoptvils
      - noaiundo